module.exports = {
  username: 'admin',
  password: 'password',
  loginUrl: 'https://example.com/login',
  loginFormSelector: '#UserLoginForm',
  usernameField: 'data[User][email]',
  passwordField: 'data[User][password]',
  logoutUrl: 'https://example.com/logout',
  downloadDir: '/home/admin/Desktop/site-download',
  baseUrl: 'https://example.com',
  downloadPaths: [
    '/account',
    '/account/image',
    '/account/security',
    '/assignments/?t=all',
    '/assignments/edit',
    '/banks/view/4',
    '/banks/view/4/assignments',
    '/banks/view/4/banks',
    '/banks/view/4/courses',
    '/banks/view/4/items',
    '/banks/view/4/leases',
    '/banks/view/4/ratings',
    '/banks/view/4/resources',
    '/banks/view/4/rubrics',
    '/banks/view/settings/4',
    '/clients/view/1',
    '/clients/view/1/banks',
    '/clients/view/1/committees',
    '/clients/view/1/ratings',
    '/clients/view/1/rubrics',
    '/clients/view/1/tests',
    '/clients/view/1/users',
    '/clients/view/settings/1',
    '/curriculums',
    '/curriculums/view?id=4dffa1d4-2e28-466d-a941-4c20c329be52',
    '/exports',
    '/gfxorders?t=all',
    '/index.php',
    '/items',
    '/items/edit/537a7adb-d074-46c7-914e-1ecc0a998d1d',
    '/items/view?id=537a7adb-d074-46c7-914e-1ecc0a998d1d',
    '/items/edit/53501f5d-1f7c-48aa-bf1b-222a0a92bb55',
    '/items/view?id=53501f5d-1f7c-48aa-bf1b-222a0a92bb55',
    '/items/edit/53500a18-e190-4bbd-94d4-222b0a92bb55',
    '/items/view?id=53500a18-e190-4bbd-94d4-222b0a92bb55',
    '/tests/view/1',
    '/tests/view/1/bookmarks',
    '/tests/view/1/discussion',
    '/tests/view/1/items',
  ]
};

